//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaDepMun.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int id { get; set; }
        public string documento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int idmun { get; set; }
        public int iddep { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Municipios Municipios { get; set; }
    }
}
